name: dbrCopilot_win.yml

on: workflow_dispatch

permissions:
  contents: read
  pull-requests: read

jobs:
  windows-tests:
    name: DBR (Windows)
    runs-on: windows-latest  # GitHub免费托管的Windows Runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install setuptools
        run: pip install setuptools

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Package VS Code Extension
        run: npx vsce package   #打包扩展文件(.vsix)

      - name: 打包当前目录(PWD)
        run: |
          # 仅排除.git相关目录和最终打包文件本身，避免递归问题
          $exclude = @('.git', 'winPWD.zip')
          Get-ChildItem -Path . -Exclude $exclude | Compress-Archive -DestinationPath winPWD.zip -Force
        shell: pwsh  # 使用PowerShell执行

      - name: Upload pwd
        uses: actions/upload-artifact@v4
        with:
          name: winPWD
          path: winPWD.zip
          retention-days: 7
          if-no-files-found: error
